 "use client";
import { FormEvent, useState } from "react";
import { createClient } from "@/lib/supabase/browser";

export default function AdminClient({initialTickets,initialUsers}:{initialTickets:any[],initialUsers:any[]}) {
 const [tickets,setTickets]=useState(initialTickets); const [users,setUsers]=useState(initialUsers); const [title,setTitle]=useState(""); const [code,setCode]=useState(""); const [msg,setMsg]=useState("");
 async function createTicket(e:FormEvent){e.preventDefault(); const sb=createClient(); const {data,error}=await sb.from("tickets").insert({title,booking_code:code,published:true,status:"PENDING"}).select().single(); if(error){setMsg(error.message);return;} setTickets([data,...tickets]);setTitle("");setCode("");setMsg("Ticket created.");}
 async function role(id:string,role:string){const {error}=await createClient().from("profiles").update({role}).eq("id",id); if(!error)setUsers(users.map(u=>u.id===id?{...u,role}:u));}
 return <main className="section"><div className="container"><p className="badge">ADMIN</p><h1>Owner Dashboard</h1><p className="muted">Manage members and publish ticket records.</p><div className="grid"><form className="card" onSubmit={createTicket}><h3>Create Daily Ticket</h3><label>Title</label><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Today’s 1.70+ Ticket" required/><label>Booking code (optional)</label><input value={code} onChange={e=>setCode(e.target.value)} placeholder="Enter manually"/><button className="button">Create Ticket</button>{msg&&<p className="success">{msg}</p>}</form><div className="card"><h3>Published Tickets</h3>{tickets.map(t=><div className="row" key={t.id}><span>{t.title}</span><span className="badge">{t.status}</span></div>)}</div></div><div className="card"><h3>Members</h3><div className="tableWrap"><table><thead><tr><th>Email</th><th>Role</th><th>Action</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td>{u.email}</td><td>{u.role}</td><td><select value={u.role} onChange={e=>role(u.id,e.target.value)}><option value="free">Free</option><option value="vip">VIP</option><option value="admin">Admin</option></select></td></tr>)}</tbody></table></div></div></div></main>
}
